In [4]:
import pandas as pd

#### We will seperately Clean all three tables that have been extracted and merge them together

In [3]:
mvps = pd.read_csv('Dataframes/mvp_votes.csv')

In [4]:
mvps

,Unnamed: 0,Rank,Player,Age,Tm,First,Pts Won,Pts Max,Share,G,...,TRB,AST,STL,BLK,FG%,3P%,FT%,WS,WS/48,Year
0,0,1,Michael Jordan,27.0,CHI,77.0,891.0,960.0,0.928,82.0,...,6.0,5.5,2.7,1.0,0.539,0.312,0.851,20.3,0.321,1991
1,1,2,Magic Johnson,31.0,LAL,10.0,497.0,960.0,0.518,79.0,...,7.0,12.5,1.3,0.2,0.477,0.320,0.906,15.4,0.251,1991
2,2,3,David Robinson,25.0,SAS,6.0,476.0,960.0,0.496,82.0,...,13.0,2.5,1.5,3.9,0.552,0.143,0.762,17.0,0.264,1991
3,3,4,Charles Barkley,27.0,PHI,2.0,222.0,960.0,0.231,67.0,...,10.1,4.2,1.6,0.5,0.570,0.284,0.722,13.4,0.258,1991
4,4,5,Karl Malone,27.0,UTA,0.0,142.0,960.0,0.148,82.0,...,11.8,3.3,1.1,1.0,0.527,0.286,0.770,15.5,0.225,1991
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
497,9,10,Jimmy Butler,33.0,MIA,0.0,3.0,1000.0,0.003,64.0,...,5.9,5.3,1.8,0.3,0.539,0.350,0.850,12.3,0.277,2023
498,10,11,De'Aaron Fox,25.0,SAC,0.0,2.0,1000.0,0.002,73.0,...,4.2,6.1,1.1,0.3,0.512,0.324,0.780,7.4,0.146,2023
499,11,12T,Jalen Brunson,26.0,NYK,0.0,1.0,1000.0,0.001,68.0,...,3.5,6.2,0.9,0.2,0.491,0.416,0.829,8.7,0.175,2023
500,12,12T,Ja Morant,23.0,MEM,0.0,1.0,1000.0,0.001,61.0,...,5.9,8.1,1.1,0.3,0.466,0.307,0.748,6.0,0.148,2023
501,13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023

In [5]:
mvps = mvps[["Player","Year","Pts Won", "Pts Max", "Share"]]

In [6]:
mvps

              Player  Year  Pts Won  Pts Max  Share
0     Michael Jordan  1991    891.0    960.0  0.928
1      Magic Johnson  1991    497.0    960.0  0.518
2     David Robinson  1991    476.0    960.0  0.496
3    Charles Barkley  1991    222.0    960.0  0.231
4        Karl Malone  1991    142.0    960.0  0.148
..               ...   ...      ...      ...    ...
497     Jimmy Butler  2023      3.0   1000.0  0.003
498     De'Aaron Fox  2023      2.0   1000.0  0.002
499    Jalen Brunson  2023      1.0   1000.0  0.001
500        Ja Morant  2023      1.0   1000.0  0.001
501              NaN  2023      NaN      NaN    NaN

[502 rows x 5 columns]

### Cleaning Player Data

In [7]:
players = pd.read_csv("Dataframes/players.csv")

In [8]:
players.isna().sum()

Unnamed: 0       0
Rk               0
Player           0
Pos              0
Age              0
Tm               0
G                0
GS               0
MP               0
FG               0
FGA              0
FG%            109
3P               0
3PA              0
3P%           2880
2P               0
2PA              0
2P%            183
eFG%           109
FT               0
FTA              0
FT%            928
ORB              0
DRB              0
TRB              0
AST              0
STL              0
BLK              0
TOV              0
PF               0
PTS              0
Year             0
dtype: int64

In [9]:
del players['Unnamed: 0']
del players['Rk']

In [10]:
players.head()

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
0,Alaa Abdelnaby,PF,22,POR,43,0,6.7,1.3,2.7,.474,...,0.6,1.4,2.1,0.3,0.1,0.3,0.5,0.9,3.1,1991
1,Mahmoud Abdul-Rauf,PG,21,DEN,67,19,22.5,6.2,15.1,.413,...,0.5,1.3,1.8,3.1,0.8,0.1,1.6,2.2,14.1,1991
2,Mark Acres,C,28,ORL,68,0,19.3,1.6,3.1,.509,...,2.1,3.2,5.3,0.4,0.4,0.4,0.6,3.2,4.2,1991
3,Michael Adams,PG,28,DEN,66,66,35.5,8.5,21.5,.394,...,0.9,3.0,3.9,10.5,2.2,0.1,3.6,2.5,26.5,1991
4,Mark Aguirre,SF,31,DET,78,13,25.7,5.4,11.7,.462,...,1.7,3.1,4.8,1.8,0.6,0.3,1.6,2.7,14.2,1991

In [11]:
#Removing rows with asterik on them to denote mvp winners
players["Player"] = players["Player"].str.replace("*","", regex=False)

Certain players played for multiple teams in a single year, we will merge their overall performance for that year into a single row

In [1]:
players.groupby(["Player", "Year"])

NameError: name 'players' is not defined

In [13]:
def single_row(df):
    if df.shape[0] == 1:
        return df
    else:
        row = df[df["Tm"] == "TOT"]
        row["Tm"] = df.iloc[-1,:]["Tm"]
        return row

players = players.groupby(["Player", "Year"]).apply(single_row)

In [14]:
players.head(20)

                                 Player Pos Age   Tm   G  GS    MP   FG   FGA  \
Player        Year
A.C. Green    1991 164       A.C. Green  PF  27  LAL  82  21  26.4  3.1   6.6
              1992 633       A.C. Green  PF  28  LAL  82  53  35.4  4.7   9.8
              1993 1092      A.C. Green  PF  29  LAL  82  55  34.4  4.6   8.6
              1994 1579      A.C. Green  PF  30  PHO  82  55  34.5  5.7  11.3
              1995 2067      A.C. Green  SF  31  PHO  82  52  32.8  3.8   7.5
              1996 2563      A.C. Green  SF  32  PHO  82  36  25.8  2.6   5.4
              1997 3138      A.C. Green  PF  33  DAL  83  73  30.0  2.8   5.8
              1998 3725      A.C. Green  PF  34  DAL  82  68  32.3  3.0   6.5
              1999 4283      A.C. Green  PF  35  DAL  50  35  18.5  2.2   5.1
              2000 4811      A.C. Green  PF  36  LAL  82  82  23.5  2.1   4.7
              2001 5330      A.C. Green  PF  37  MIA  82   1  17.2  1.8   4.0
A.J. Bramlett 2000 4684   A.J. Bramlett   C  23  CLE   8   0   7.6  0.5   2.6
A.J. English  1991 127     A.J. English  SG  23  WSB  70  12  20.6  3.6   8.2
              1992 597     A.J. English  SG  24  WSB  81   6  20.6  4.5  10.4
A.J. Green    2023 19115     A.J. Green  SG  23  MIL  35   1   9.9  1.5   3.6
A.J. Guyton   2001 5333     A.J. Guyton  PG  22  CHI  33   8  19.1  2.4   5.8
              2002 5886     A.J. Guyton  PG  23  CHI  45   6  13.5  2.0   5.4
              2003 6393     A.J. Guyton  PG  24  GSW   2   0   4.5  0.0   2.0
A.J. Hammons  2017 14814   A.J. Hammons   C  24  DAL  22   0   7.4  0.8   1.9
A.J. Lawson   2023 19259    A.J. Lawson  SG  22  DAL  15   0   7.2  1.5   2.9

                           FG%  ...  ORB  DRB  TRB  AST  STL  BLK  TOV   PF  \
Player        Year              ...
A.C. Green    1991 164    .476  ...  2.5  3.8  6.3  0.9  0.7  0.3  1.2  1.4
              1992 633    .476  ...  3.7  5.6  9.3  1.4  1.1  0.4  1.4  1.7
              1993 1092   .537  ...  3.5  5.2  8.7  1.4  1.1  0.5  1.4  1.8
              1994 1579   .502  ...  3.4  5.8  9.2  1.7  0.9  0.5  1.2  1.7
              1995 2067   .504  ...  2.4  5.8  8.2  1.5  0.7  0.4  1.4  1.8
              1996 2563   .484  ...  2.0  4.7  6.8  0.9  0.5  0.3  1.0  1.7
              1997 3138   .483  ...  2.7  5.2  7.9  0.8  0.8  0.2  0.9  1.7
              1998 3725   .453  ...  2.7  5.5  8.1  1.5  1.0  0.3  0.8  1.9
              1999 4283   .422  ...  1.6  2.9  4.6  0.5  0.6  0.2  0.4  1.4
              2000 4811   .447  ...  2.0  4.0  5.9  1.0  0.6  0.2  0.6  1.5
              2001 5330   .444  ...  1.3  2.5  3.8  0.5  0.4  0.1  0.5  1.5
A.J. Bramlett 2000 4684   .190  ...  1.5  1.3  2.8  0.0  0.1  0.0  0.4  1.6
A.J. English  1991 127    .439  ...  0.9  1.2  2.1  2.5  0.4  0.2  1.6  1.8
              1992 597    .433  ...  0.9  1.2  2.1  1.8  0.4  0.1  1.1  2.0
A.J. Green    2023 19115  .424  ...  0.2  1.1  1.3  0.6  0.2  0.0  0.3  0.9
A.J. Guyton   2001 5333   .406  ...  0.3  0.8  1.1  1.9  0.3  0.2  0.7  1.1
              2002 5886   .361  ...  0.3  0.7  1.0  1.8  0.2  0.2  0.8  0.5
              2003 6393   .000  ...  0.0  0.0  0.0  1.0  0.5  0.0  0.5  0.0
A.J. Hammons  2017 14814  .405  ...  0.4  1.3  1.6  0.2  0.0  0.6  0.5  1.0
A.J. Lawson   2023 19259  .500  ...  0.4  1.0  1.4  0.1  0.1  0.0  0.2  0.7

                           PTS  Year
Player        Year
A.C. Green    1991 164     9.1  1991
              1992 633    13.6  1992
              1993 1092   12.8  1993
              1994 1579   14.7  1994
              1995 2067   11.2  1995
              1996 2563    7.5  1996
              1997 3138    7.2  1997
              1998 3725    7.3  1998
              1999 4283    4.9  1999
              2000 4811    5.0  2000
              2001 5330    4.5  2001
A.J. Bramlett 2000 4684    1.0  2000
A.J. English  1991 127     8.8  1991
              1992 597    10.9  1992
A.J. Green    2023 19115   4.4  2023
A.J. Guyton   2001 5333    6.0  2001
              2002 5886    5.4  2002
              2003 6393    0.0  2003
A.J. Hammons  2017 14814   2.2  2017
A.J. Lawson   2023 19259   3.7  2023

[20 rows x 30 columns]

In [15]:
players.index = players.index.droplevel()

In [16]:
players.index = players.index.droplevel()

In [123]:
df = players.merge(mvps, how = "outer", on =["Player", "Year"])

In [124]:
df

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,AST,STL,BLK,TOV,PF,PTS,Year,Pts Won,Pts Max,Share
0,A.C. Green,PF,27,LAL,82,21,26.4,3.1,6.6,.476,...,0.9,0.7,0.3,1.2,1.4,9.1,1991,NaN,NaN,NaN
1,A.C. Green,PF,28,LAL,82,53,35.4,4.7,9.8,.476,...,1.4,1.1,0.4,1.4,1.7,13.6,1992,NaN,NaN,NaN
2,A.C. Green,PF,29,LAL,82,55,34.4,4.6,8.6,.537,...,1.4,1.1,0.5,1.4,1.8,12.8,1993,NaN,NaN,NaN
3,A.C. Green,PF,30,PHO,82,55,34.5,5.7,11.3,.502,...,1.7,0.9,0.5,1.2,1.7,14.7,1994,NaN,NaN,NaN
4,A.C. Green,SF,31,PHO,82,52,32.8,3.8,7.5,.504,...,1.5,0.7,0.4,1.4,1.8,11.2,1995,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15234,Željko Rebrača,C,32,LAC,58,2,16.0,2.3,4.0,.568,...,0.4,0.2,0.7,0.8,2.2,5.8,2005,NaN,NaN,NaN
15235,Željko Rebrača,C,33,LAC,29,2,14.2,1.8,3.3,.542,...,0.3,0.2,0.7,0.8,2.0,4.7,2006,NaN,NaN,NaN
15236,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2021,NaN,NaN,NaN
15237,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2022,NaN,NaN,NaN
15238,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2023,NaN,NaN,NaN

In [125]:
df[df["Pts Won"]  == 0]

Empty DataFrame
Columns: [Player, Pos, Age, Tm, G, GS, MP, FG, FGA, FG%, 3P, 3PA, 3P%, 2P, 2PA, 2P%, eFG%, FT, FTA, FT%, ORB, DRB, TRB, AST, STL, BLK, TOV, PF, PTS, Year, Pts Won, Pts Max, Share]
Index: []

[0 rows x 33 columns]

In [126]:
df[['Pts Won', 'Pts Max', 'Share']] = df[['Pts Won', 'Pts Max', 'Share']].fillna(0)

In [127]:
df.tail()

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,AST,STL,BLK,TOV,PF,PTS,Year,Pts Won,Pts Max,Share
15234,Željko Rebrača,C,32,LAC,58,2,16.0,2.3,4.0,.568,...,0.4,0.2,0.7,0.8,2.2,5.8,2005,0.0,0.0,0.0
15235,Željko Rebrača,C,33,LAC,29,2,14.2,1.8,3.3,.542,...,0.3,0.2,0.7,0.8,2.0,4.7,2006,0.0,0.0,0.0
15236,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2021,0.0,0.0,0.0
15237,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2022,0.0,0.0,0.0
15238,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2023,0.0,0.0,0.0

### Cleaning Team Data

In [5]:
teams = pd.read_csv('Dataframes/teams_standings.csv')

In [6]:
teams.head(30)

,Unnamed: 0,W,L,W/L%,GB,PS/G,PA/G,SRS,Years,Team
0,0,56,26,.683,—,111.5,105.7,5.22,1991,Boston Celtics*
1,1,44,38,.537,12.0,105.4,105.6,-0.39,1991,Philadelphia 76ers*
2,2,39,43,.476,17.0,103.1,103.3,-0.43,1991,New York Knicks*
3,3,30,52,.366,26.0,101.4,106.4,-4.84,1991,Washington Bullets
4,4,26,56,.317,30.0,102.9,107.5,-4.53,1991,New Jersey Nets
5,5,24,58,.293,32.0,101.8,107.8,-5.91,1991,Miami Heat
6,6,Central Division,Central Division,Central Division,Central Division,Central Division,Central Division,Central Division,1991,Central Division
7,7,61,21,.744,—,110.0,101.0,8.57,1991,Chicago Bulls*
8,8,50,32,.610,11.0,100.1,96.8,3.08,1991,Detroit Pistons*
9,9,48,34,.585,13.0,106.4,104.0,2.33,1991,Milwaukee Bucks*
10,10,43,39,.524,18.0,109.8,109.0,0.72,1991,Atlanta Hawks*
11,11,41,41,.500,20.0,111.7,112.1,-0.37,1991,Indiana Pacers*
12,12,33,49,.402,28.0,101.7,104.2,-2.33,1991,Cleveland Cavaliers
13,13,26,56,.317,35.0,102.8,108.0,-4.95,1991,Charlotte Hornets
14,0,Midwest Division,Midwest Division,Midwest Division,Midwest Division,Midwest Division,Midwest Division,Midwest Division,1991,Midwest Division
15,1,55,27,.671,—,107.1,102.6,4.30,1991,San Antonio Spurs*
16,2,54,28,.659,1.0,104.0,100.7,3.18,1991,Utah Jazz*
17,3,52,30,.634,3.0,106.7,103.2,3.27,1991,Houston Rockets*
18,4,31,51,.378,24.0,105.9,109.9,-3.79,1991,Orlando Magic
19,5,29,53,.354,26.0,99.6,103.5,-3.75,1991,Minnesota Timberwolves
20,6,28,54,.341,27.0,99.9,104.5,-4.27,1991,Dallas Mavericks
21,7,20,62,.244,35.0,119.9,130.8,-10.31,1991,Denver Nuggets
22,8,Pacific Division,Pacific Division,Pacific Division,Pacific Division,Pacific Division,Pacific Division,Pacific Division,1991,Pacific Division
23,9,63,19,.768,—,114.7,106.0,8.47,1991,Portland Trail Blazers*
24,10,58,24,.707,5.0,106.3,99.6,6.73,1991,Los Angeles Lakers*
25,11,55,27,.671,8.0,114.0,107.5,6.49,1991,Phoenix Suns*
26,12,44,38,.537,19.0,116.6,115.0,1.72,1991,Golden State Warriors*
27,13,41,41,.500,22.0,106.6,105.4,1.31,1991,Seattle SuperSonics*
28,14,31,51,.378,32.0,103.5,107.0,-3.16,1991,Los Angeles Clippers
29,15,25,57,.305,38.0,96.7,103.5,-6.27,1991,Sacramento Kings

In [7]:
teams = teams[~teams['W'].str.contains("Division")]

In [8]:
teams.head(30)

,Unnamed: 0,W,L,W/L%,GB,PS/G,PA/G,SRS,Years,Team
0,0,56,26,.683,—,111.5,105.7,5.22,1991,Boston Celtics*
1,1,44,38,.537,12.0,105.4,105.6,-0.39,1991,Philadelphia 76ers*
2,2,39,43,.476,17.0,103.1,103.3,-0.43,1991,New York Knicks*
3,3,30,52,.366,26.0,101.4,106.4,-4.84,1991,Washington Bullets
4,4,26,56,.317,30.0,102.9,107.5,-4.53,1991,New Jersey Nets
5,5,24,58,.293,32.0,101.8,107.8,-5.91,1991,Miami Heat
7,7,61,21,.744,—,110.0,101.0,8.57,1991,Chicago Bulls*
8,8,50,32,.610,11.0,100.1,96.8,3.08,1991,Detroit Pistons*
9,9,48,34,.585,13.0,106.4,104.0,2.33,1991,Milwaukee Bucks*
10,10,43,39,.524,18.0,109.8,109.0,0.72,1991,Atlanta Hawks*
11,11,41,41,.500,20.0,111.7,112.1,-0.37,1991,Indiana Pacers*
12,12,33,49,.402,28.0,101.7,104.2,-2.33,1991,Cleveland Cavaliers
13,13,26,56,.317,35.0,102.8,108.0,-4.95,1991,Charlotte Hornets
15,1,55,27,.671,—,107.1,102.6,4.30,1991,San Antonio Spurs*
16,2,54,28,.659,1.0,104.0,100.7,3.18,1991,Utah Jazz*
17,3,52,30,.634,3.0,106.7,103.2,3.27,1991,Houston Rockets*
18,4,31,51,.378,24.0,105.9,109.9,-3.79,1991,Orlando Magic
19,5,29,53,.354,26.0,99.6,103.5,-3.75,1991,Minnesota Timberwolves
20,6,28,54,.341,27.0,99.9,104.5,-4.27,1991,Dallas Mavericks
21,7,20,62,.244,35.0,119.9,130.8,-10.31,1991,Denver Nuggets
23,9,63,19,.768,—,114.7,106.0,8.47,1991,Portland Trail Blazers*
24,10,58,24,.707,5.0,106.3,99.6,6.73,1991,Los Angeles Lakers*
25,11,55,27,.671,8.0,114.0,107.5,6.49,1991,Phoenix Suns*
26,12,44,38,.537,19.0,116.6,115.0,1.72,1991,Golden State Warriors*
27,13,41,41,.500,22.0,106.6,105.4,1.31,1991,Seattle SuperSonics*
28,14,31,51,.378,32.0,103.5,107.0,-3.16,1991,Los Angeles Clippers
29,15,25,57,.305,38.0,96.7,103.5,-6.27,1991,Sacramento Kings
30,0,51,31,.622,—,106.6,103.0,3.41,1992,Boston Celtics*
31,1,51,31,.622,—,101.6,97.7,3.67,1992,New York Knicks*
32,2,40,42,.488,11.0,105.4,107.1,-1.54,1992,New Jersey Nets*

In [9]:
teams['Team'] = teams['Team'].str.replace('*',"",regex=False)

In [10]:
del teams['Unnamed: 0']

In [11]:
teams.head(30)

     W   L  W/L%    GB   PS/G   PA/G     SRS  Years                    Team
0   56  26  .683     —  111.5  105.7    5.22   1991          Boston Celtics
1   44  38  .537  12.0  105.4  105.6   -0.39   1991      Philadelphia 76ers
2   39  43  .476  17.0  103.1  103.3   -0.43   1991         New York Knicks
3   30  52  .366  26.0  101.4  106.4   -4.84   1991      Washington Bullets
4   26  56  .317  30.0  102.9  107.5   -4.53   1991         New Jersey Nets
5   24  58  .293  32.0  101.8  107.8   -5.91   1991              Miami Heat
7   61  21  .744     —  110.0  101.0    8.57   1991           Chicago Bulls
8   50  32  .610  11.0  100.1   96.8    3.08   1991         Detroit Pistons
9   48  34  .585  13.0  106.4  104.0    2.33   1991         Milwaukee Bucks
10  43  39  .524  18.0  109.8  109.0    0.72   1991           Atlanta Hawks
11  41  41  .500  20.0  111.7  112.1   -0.37   1991          Indiana Pacers
12  33  49  .402  28.0  101.7  104.2   -2.33   1991     Cleveland Cavaliers
13  26  56  .317  35.0  102.8  108.0   -4.95   1991       Charlotte Hornets
15  55  27  .671     —  107.1  102.6    4.30   1991       San Antonio Spurs
16  54  28  .659   1.0  104.0  100.7    3.18   1991               Utah Jazz
17  52  30  .634   3.0  106.7  103.2    3.27   1991         Houston Rockets
18  31  51  .378  24.0  105.9  109.9   -3.79   1991           Orlando Magic
19  29  53  .354  26.0   99.6  103.5   -3.75   1991  Minnesota Timberwolves
20  28  54  .341  27.0   99.9  104.5   -4.27   1991        Dallas Mavericks
21  20  62  .244  35.0  119.9  130.8  -10.31   1991          Denver Nuggets
23  63  19  .768     —  114.7  106.0    8.47   1991  Portland Trail Blazers
24  58  24  .707   5.0  106.3   99.6    6.73   1991      Los Angeles Lakers
25  55  27  .671   8.0  114.0  107.5    6.49   1991            Phoenix Suns
26  44  38  .537  19.0  116.6  115.0    1.72   1991   Golden State Warriors
27  41  41  .500  22.0  106.6  105.4    1.31   1991     Seattle SuperSonics
28  31  51  .378  32.0  103.5  107.0   -3.16   1991    Los Angeles Clippers
29  25  57  .305  38.0   96.7  103.5   -6.27   1991        Sacramento Kings
30  51  31  .622     —  106.6  103.0    3.41   1992          Boston Celtics
31  51  31  .622     —  101.6   97.7    3.67   1992         New York Knicks
32  40  42  .488  11.0  105.4  107.1   -1.54   1992         New Jersey Nets

In [12]:
nicknames = {}

with open("Dataframes/nicknames.txt") as f:
    lines = f.readlines()
    for line in lines[1:]:
       abbrev, name =  line.replace("\n" , "").split(",")
       nicknames[abbrev] = name

In [13]:
nicknames

{'ATL': 'Atlanta Hawks',
 'BRK': 'Brooklyn Nets',
 'BKN': 'Brooklyn Nets',
 'BOS': 'Boston Celtics',
 'CHA': 'Charlotte Bobcats',
 'CHH': 'Charlotte Hornets',
 'CHO': 'Charlotte Hornets',
 'CHI': 'Chicago Bulls',
 'CLE': 'Cleveland Cavaliers',
 'DAL': 'Dallas Mavericks',
 'DEN': 'Denver Nuggets',
 'DET': 'Detroit Pistons',
 'GSW': 'Golden State Warriors',
 'HOU': 'Houston Rockets',
 'IND': 'Indiana Pacers',
 'LAC': 'Los Angeles Clippers',
 'LAL': 'Los Angeles Lakers',
 'MEM': 'Memphis Grizzlies',
 'MIA': 'Miami Heat',
 'MIL': 'Milwaukee Bucks',
 'MIN': 'Minnesota Timberwolves',
 'NJN': 'New Jersey Nets',
 'NOH': 'New Orleans Hornets',
 'NOP': 'New Orleans Pelicans',
 'NOK': 'New Orleans/Oklahoma City Hornets',
 'NYK': 'New York Knicks',
 'OKC': 'Oklahoma City Thunder',
 'ORL': 'Orlando Magic',
 'PHI': 'Philadelphia 76ers',
 'PHX': 'Phoenix Suns',
 'PHO': 'Phoenix Suns',
 'POR': 'Portland Trail Blazers',
 'SEA': 'Seattle SuperSonics',
 'SAC': 'Sacramento Kings',
 'SAS': 'San Antonio Spurs',
 'TOR': 'Toronto Raptors',
 'UTA': 'Utah Jazz',
 'VAN': 'Vancouver Grizzlies',
 'WAS': 'Washington Wizards',
 'WSB': 'Washington Bullets'}

In [14]:
df['Team'] = df['Tm'].map(nicknames)

NameError: name 'df' is not defined

In [138]:
df.head(10)

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,STL,BLK,TOV,PF,PTS,Year,Pts Won,Pts Max,Share,Team
0,A.C. Green,PF,27,LAL,82,21,26.4,3.1,6.6,.476,...,0.7,0.3,1.2,1.4,9.1,1991,0.0,0.0,0.0,Los Angeles Lakers
1,A.C. Green,PF,28,LAL,82,53,35.4,4.7,9.8,.476,...,1.1,0.4,1.4,1.7,13.6,1992,0.0,0.0,0.0,Los Angeles Lakers
2,A.C. Green,PF,29,LAL,82,55,34.4,4.6,8.6,.537,...,1.1,0.5,1.4,1.8,12.8,1993,0.0,0.0,0.0,Los Angeles Lakers
3,A.C. Green,PF,30,PHO,82,55,34.5,5.7,11.3,.502,...,0.9,0.5,1.2,1.7,14.7,1994,0.0,0.0,0.0,Phoenix Suns
4,A.C. Green,SF,31,PHO,82,52,32.8,3.8,7.5,.504,...,0.7,0.4,1.4,1.8,11.2,1995,0.0,0.0,0.0,Phoenix Suns
5,A.C. Green,SF,32,PHO,82,36,25.8,2.6,5.4,.484,...,0.5,0.3,1.0,1.7,7.5,1996,0.0,0.0,0.0,Phoenix Suns
6,A.C. Green,PF,33,DAL,83,73,30.0,2.8,5.8,.483,...,0.8,0.2,0.9,1.7,7.2,1997,0.0,0.0,0.0,Dallas Mavericks
7,A.C. Green,PF,34,DAL,82,68,32.3,3.0,6.5,.453,...,1.0,0.3,0.8,1.9,7.3,1998,0.0,0.0,0.0,Dallas Mavericks
8,A.C. Green,PF,35,DAL,50,35,18.5,2.2,5.1,.422,...,0.6,0.2,0.4,1.4,4.9,1999,0.0,0.0,0.0,Dallas Mavericks
9,A.C. Green,PF,36,LAL,82,82,23.5,2.1,4.7,.447,...,0.6,0.2,0.6,1.5,5.0,2000,0.0,0.0,0.0,Los Angeles Lakers

In [139]:
teams['Year'] = teams['Years']

In [140]:
del teams['Years']
teams.head()

    W   L  W/L%    GB   PS/G   PA/G    SRS                Team  Year
0  56  26  .683     —  111.5  105.7   5.22      Boston Celtics  1991
1  44  38  .537  12.0  105.4  105.6  -0.39  Philadelphia 76ers  1991
2  39  43  .476  17.0  103.1  103.3  -0.43     New York Knicks  1991
3  30  52  .366  26.0  101.4  106.4  -4.84  Washington Bullets  1991
4  26  56  .317  30.0  102.9  107.5  -4.53     New Jersey Nets  1991

In [141]:
nba_stats = df.merge(teams, how='outer', on=['Team', 'Year'])

In [142]:
nba_stats

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,Pts Max,Share,Team,W,L,W/L%,GB,PS/G,PA/G,SRS
0,A.C. Green,PF,27,LAL,82,21,26.4,3.1,6.6,.476,...,0.0,0.0,Los Angeles Lakers,58,24,.707,5.0,106.3,99.6,6.73
1,Byron Scott,SG,29,LAL,82,82,32.1,6.1,12.8,.477,...,0.0,0.0,Los Angeles Lakers,58,24,.707,5.0,106.3,99.6,6.73
2,Elden Campbell,PF,22,LAL,52,0,7.3,1.1,2.4,.455,...,0.0,0.0,Los Angeles Lakers,58,24,.707,5.0,106.3,99.6,6.73
3,Irving Thomas,PF,25,LAL,26,0,4.2,0.7,1.9,.340,...,0.0,0.0,Los Angeles Lakers,58,24,.707,5.0,106.3,99.6,6.73
4,James Worthy,SF,29,LAL,78,74,38.6,9.2,18.7,.492,...,0.0,0.0,Los Angeles Lakers,58,24,.707,5.0,106.3,99.6,6.73
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15234,Thon Maker,C,19,MIL,57,34,9.9,1.5,3.2,.459,...,0.0,0.0,Milwaukee Bucks,42,40,.512,9.0,103.6,103.8,-0.45
15235,Tony Snell,SG,25,MIL,80,80,29.2,3.1,6.8,.455,...,0.0,0.0,Milwaukee Bucks,42,40,.512,9.0,103.6,103.8,-0.45
15236,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15237,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15238,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [143]:
nba_stats = nba_stats.apply(pd.to_numeric, errors='ignore')

nba_stats.dtypes

Player      object
Pos         object
Age        float64
Tm          object
G          float64
GS         float64
MP         float64
FG         float64
FGA        float64
FG%        float64
3P         float64
3PA        float64
3P%        float64
2P         float64
2PA        float64
2P%        float64
eFG%       float64
FT         float64
FTA        float64
FT%        float64
ORB        float64
DRB        float64
TRB        float64
AST        float64
STL        float64
BLK        float64
TOV        float64
PF         float64
PTS        float64
Year         int64
Pts Won    float64
Pts Max    float64
Share      float64
Team        object
W          float64
L          float64
W/L%       float64
GB          object
PS/G       float64
PA/G       float64
SRS        float64
dtype: object

In [144]:
nba_stats["GB"] = pd.to_numeric(nba_stats["GB"].str.replace("—","0"))

In [145]:
nba_stats.dtypes

Player      object
Pos         object
Age        float64
Tm          object
G          float64
GS         float64
MP         float64
FG         float64
FGA        float64
FG%        float64
3P         float64
3PA        float64
3P%        float64
2P         float64
2PA        float64
2P%        float64
eFG%       float64
FT         float64
FTA        float64
FT%        float64
ORB        float64
DRB        float64
TRB        float64
AST        float64
STL        float64
BLK        float64
TOV        float64
PF         float64
PTS        float64
Year         int64
Pts Won    float64
Pts Max    float64
Share      float64
Team        object
W          float64
L          float64
W/L%       float64
GB         float64
PS/G       float64
PA/G       float64
SRS        float64
dtype: object

In [146]:
nba_stats.tail()

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,Pts Max,Share,Team,W,L,W/L%,GB,PS/G,PA/G,SRS
15234,Thon Maker,C,19.0,MIL,57.0,34.0,9.9,1.5,3.2,0.459,...,0.0,0.0,Milwaukee Bucks,42.0,40.0,0.512,9.0,103.6,103.8,-0.45
15235,Tony Snell,SG,25.0,MIL,80.0,80.0,29.2,3.1,6.8,0.455,...,0.0,0.0,Milwaukee Bucks,42.0,40.0,0.512,9.0,103.6,103.8,-0.45
15236,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15237,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15238,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [147]:
nba_stats.isna().sum()

Player        3
Pos           3
Age           3
Tm            3
G             3
GS            3
MP            3
FG            3
FGA           3
FG%          64
3P            3
3PA           3
3P%        2105
2P            3
2PA           3
2P%         108
eFG%         64
FT            3
FTA           3
FT%         548
ORB           3
DRB           3
TRB           3
AST           3
STL           3
BLK           3
TOV           3
PF            3
PTS           3
Year          0
Pts Won       0
Pts Max       0
Share         0
Team          3
W             3
L             3
W/L%          3
GB            3
PS/G          3
PA/G          3
SRS           3
dtype: int64

In [148]:
nba_stats.to_csv("mvp_stats_df1.csv")

In [64]:
df1 = pd.read_csv('player_mvp_stats.csv')

In [65]:
df1

,Unnamed: 0,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,Pts Max,Share,Team,W,L,W/L%,GB,PS/G,PA/G,SRS
0,0,A.C. Green,PF,27,LAL,82,21,26.4,3.1,6.6,...,0.0,0.0,Los Angeles Lakers,58,24,0.707,5.0,106.3,99.6,6.73
1,1,Byron Scott,SG,29,LAL,82,82,32.1,6.1,12.8,...,0.0,0.0,Los Angeles Lakers,58,24,0.707,5.0,106.3,99.6,6.73
2,2,Elden Campbell,PF,22,LAL,52,0,7.3,1.1,2.4,...,0.0,0.0,Los Angeles Lakers,58,24,0.707,5.0,106.3,99.6,6.73
3,3,Irving Thomas,PF,25,LAL,26,0,4.2,0.7,1.9,...,0.0,0.0,Los Angeles Lakers,58,24,0.707,5.0,106.3,99.6,6.73
4,4,James Worthy,SF,29,LAL,78,74,38.6,9.2,18.7,...,0.0,0.0,Los Angeles Lakers,58,24,0.707,5.0,106.3,99.6,6.73
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15231,15231,Spencer Hawes,PF,28,MIL,54,1,14.8,2.5,5.1,...,0.0,0.0,Milwaukee Bucks,42,40,0.512,9.0,103.6,103.8,-0.45
15232,15232,Steve Novak,PF,33,MIL,8,0,2.8,0.3,0.9,...,0.0,0.0,Milwaukee Bucks,42,40,0.512,9.0,103.6,103.8,-0.45
15233,15233,Terrence Jones,PF,25,MIL,54,12,23.5,4.3,9.1,...,0.0,0.0,Milwaukee Bucks,42,40,0.512,9.0,103.6,103.8,-0.45
15234,15234,Thon Maker,C,19,MIL,57,34,9.9,1.5,3.2,...,0.0,0.0,Milwaukee Bucks,42,40,0.512,9.0,103.6,103.8,-0.45
15235,15235,Tony Snell,SG,25,MIL,80,80,29.2,3.1,6.8,...,0.0,0.0,Milwaukee Bucks,42,40,0.512,9.0,103.6,103.8,-0.45

In [110]:
del df1['Unnamed: 0']

In [111]:
df1.to_csv('player_mvp_stats.csv')

In [112]:
df1

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,Pts Max,Share,Team,W,L,W/L%,GB,PS/G,PA/G,SRS
0,A.C. Green,PF,27,LAL,82,21,26.4,3.1,6.6,0.476,...,0,0.000,Los Angeles Lakers,58,24,0.707,5.0,106.3,99.6,6.73
1,Byron Scott,SG,29,LAL,82,82,32.1,6.1,12.8,0.477,...,0,0.000,Los Angeles Lakers,58,24,0.707,5.0,106.3,99.6,6.73
2,Elden Campbell,PF,22,LAL,52,0,7.3,1.1,2.4,0.455,...,0,0.000,Los Angeles Lakers,58,24,0.707,5.0,106.3,99.6,6.73
3,Irving Thomas,PF,25,LAL,26,0,4.2,0.7,1.9,0.340,...,0,0.000,Los Angeles Lakers,58,24,0.707,5.0,106.3,99.6,6.73
4,James Worthy,SF,29,LAL,78,74,38.6,9.2,18.7,0.492,...,0,0.000,Los Angeles Lakers,58,24,0.707,5.0,106.3,99.6,6.73
5,Larry Drew,PG,32,LAL,48,2,10.3,1.1,2.6,0.432,...,0,0.000,Los Angeles Lakers,58,24,0.707,5.0,106.3,99.6,6.73
6,Magic Johnson,PG,31,LAL,79,79,37.1,5.9,12.4,0.477,...,960,0.518,Los Angeles Lakers,58,24,0.707,5.0,106.3,99.6,6.73
7,Mychal Thompson,C,36,LAL,72,4,15.0,1.6,3.2,0.496,...,0,0.000,Los Angeles Lakers,58,24,0.707,5.0,106.3,99.6,6.73
8,Sam Perkins,PF,29,LAL,73,66,34.3,5.0,10.2,0.495,...,0,0.000,Los Angeles Lakers,58,24,0.707,5.0,106.3,99.6,6.73
9,Terry Teagle,SG,30,LAL,82,0,18.3,4.1,9.2,0.443,...,0,0.000,Los Angeles Lakers,58,24,0.707,5.0,106.3,99.6,6.73
10,Tony Smith,SG,22,LAL,64,1,10.9,1.5,3.4,0.441,...,0,0.000,Los Angeles Lakers,58,24,0.707,5.0,106.3,99.6,6.73
11,Vlade Divac,C,22,LAL,82,81,28.2,4.4,7.8,0.565,...,0,0.000,Los Angeles Lakers,58,24,0.707,5.0,106.3,99.6,6.73
12,A.C. Green,PF,28,LAL,82,53,35.4,4.7,9.8,0.476,...,0,0.000,Los Angeles Lakers,43,39,0.524,14.0,100.4,101.5,-0.95
13,Byron Scott,SG,30,LAL,82,82,32.7,5.6,12.3,0.458,...,0,0.000,Los Angeles Lakers,43,39,0.524,14.0,100.4,101.5,-0.95
14,Chucky Brown,SF,23,LAL,42,2,10.3,1.4,3.0,0.469,...,0,0.000,Los Angeles Lakers,43,39,0.524,14.0,100.4,101.5,-0.95
15,Cliff Robinson,PF,31,LAL,9,0,8.7,1.2,3.0,0.407,...,0,0.000,Los Angeles Lakers,43,39,0.524,14.0,100.4,101.5,-0.95
16,Demetrius Calip,PG,22,LAL,7,0,8.3,0.6,2.6,0.222,...,0,0.000,Los Angeles Lakers,43,39,0.524,14.0,100.4,101.5,-0.95
17,Elden Campbell,C,23,LAL,81,47,23.2,2.7,6.1,0.448,...,0,0.000,Los Angeles Lakers,43,39,0.524,14.0,100.4,101.5,-0.95
18,Jack Haley,C,28,LAL,49,9,8.0,0.6,1.7,0.369,...,0,0.000,Los Angeles Lakers,43,39,0.524,14.0,100.4,101.5,-0.95
19,James Worthy,SF,30,LAL,54,54,39.0,8.3,18.6,0.447,...,0,0.000,Los Angeles Lakers,43,39,0.524,14.0,100.4,101.5,-0.95
20,Keith Owens,SF,22,LAL,20,0,4.0,0.5,1.6,0.281,...,0,0.000,Los Angeles Lakers,43,39,0.524,14.0,100.4,101.5,-0.95
21,Rory Sparrow,PG,33,LAL,46,0,10.6,1.3,3.3,0.384,...,0,0.000,Los Angeles Lakers,43,39,0.524,14.0,100.4,101.5,-0.95
22,Sam Perkins,PF,30,LAL,63,63,37.0,5.7,12.7,0.450,...,0,0.000,Los Angeles Lakers,43,39,0.524,14.0,100.4,101.5,-0.95
23,Sedale Threatt,PG,30,LAL,82,82,37.4,6.2,12.7,0.489,...,0,0.000,Los Angeles Lakers,43,39,0.524,14.0,100.4,101.5,-0.95
24,Terry Teagle,SG,31,LAL,82,0,19.5,4.4,9.8,0.452,...,0,0.000,Los Angeles Lakers,43,39,0.524,14.0,100.4,101.5,-0.95
25,Tony Smith,PG,23,LAL,63,0,13.0,1.8,4.5,0.399,...,0,0.000,Los Angeles Lakers,43,39,0.524,14.0,100.4,101.5,-0.95
26,Vlade Divac,C,23,LAL,36,18,27.2,4.4,8.8,0.495,...,0,0.000,Los Angeles Lakers,43,39,0.524,14.0,100.4,101.5,-0.95
27,A.C. Green,PF,29,LAL,82,55,34.4,4.6,8.6,0.537,...,0,0.000,Los Angeles Lakers,39,43,0.476,23.0,104.2,105.5,-1.20
28,Alex Blackwell,SF,22,LAL,27,0,4.0,0.5,1.6,0.333,...,0,0.000,Los Angeles Lakers,39,43,0.476,23.0,104.2,105.5,-1.20
29,Anthony Peeler,SG,23,LAL,77,11,21.5,3.9,8.2,0.468,...,0,0.000,Los Angeles Lakers,39,43,0.476,23.0,104.2,105.5,-1.20

In [113]:
stats1 = pd.read_csv('player_mvp_stats.csv')

,Unnamed: 0,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,Pts Max,Share,Team,W,L,W/L%,GB,PS/G,PA/G,SRS
15231,15231,Spencer Hawes,PF,28,MIL,54,1,14.8,2.5,5.1,...,0,0.0,Milwaukee Bucks,42,40,0.512,9.0,103.6,103.8,-0.45
15232,15232,Steve Novak,PF,33,MIL,8,0,2.8,0.3,0.9,...,0,0.0,Milwaukee Bucks,42,40,0.512,9.0,103.6,103.8,-0.45
15233,15233,Terrence Jones,PF,25,MIL,54,12,23.5,4.3,9.1,...,0,0.0,Milwaukee Bucks,42,40,0.512,9.0,103.6,103.8,-0.45
15234,15234,Thon Maker,C,19,MIL,57,34,9.9,1.5,3.2,...,0,0.0,Milwaukee Bucks,42,40,0.512,9.0,103.6,103.8,-0.45
15235,15235,Tony Snell,SG,25,MIL,80,80,29.2,3.1,6.8,...,0,0.0,Milwaukee Bucks,42,40,0.512,9.0,103.6,103.8,-0.45